build(deps): bump org.openrewrite.recipe:rewrite-migrate-java from 3.23.0 to 3.24.0 in /lyo-client-samples (#301)
* build(deps): bump org.openrewrite.recipe:rewrite-migrate-java

Bumps [org.openrewrite.recipe:rewrite-migrate-java](https://github.com/openrewrite/rewrite-migrate-java) from 3.23.0 to 3.24.0.
- [Release notes](https://github.com/openrewrite/rewrite-migrate-java/releases)
- [Commits](https://github.com/openrewrite/rewrite-migrate-java/compare/v3.23.0...v3.24.0)

---
updated-dependencies:
- dependency-name: org.openrewrite.recipe:rewrite-migrate-java
  dependency-version: 3.24.0
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

* build: run rewrite on build

* build: add compiler version and do not use non-existent profile

* build: account for newlines

* debug

* chore: reformat """ literals

Signed-off-by: Andrew Berezovskyi <andriib@kth.se>

* chore: lombok and junit best practices

Signed-off-by: Andrew Berezovskyi <andriib@kth.se>

* chore: undo debug

---------

Signed-off-by: dependabot[bot] <support@github.com>
Signed-off-by: Andrew Berezovskyi <andriib@kth.se>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Andrew Berezovskyi <andrew@berezovskyi.me>
Co-authored-by: Andrew Berezovskyi <andriib@kth.se>

diff --git a/.github/workflows/maven-client.yml b/.github/workflows/maven-client.yml
--- a/.github/workflows/maven-client.yml
+++ b/.github/workflows/maven-client.yml
@@ -45,6 +45,28 @@ jobs:
       - name: Build Lyo Client samples
         run: |
           mvn -B clean verify --file lyo-client-samples/pom.xml
-      - name: Enforce code style
+      - name: Run Spotless (Maven plugin)
         run: |
-          mvn -B spotless:check --file lyo-client-samples/pom.xml
+          # set -x
+          mvn -B spotless:apply --file lyo-client-samples/pom.xml
+          # git -C ./ status --porcelain
+          git add -A
+          # git -C ./ status --porcelain
+          if [ -z "$(git -C ./ status --porcelain)" ]; then
+            echo "Spotless PASS"
+          else
+            git -C ./ status --porcelain
+            echo "Spotless FAIL; run 'mvn -B spotless:apply --file lyo-client-samples/pom.xml' locally" >&2
+            exit 1
+          fi
+      - name: Run OpenRewrite (Maven plugin)
+        run: |
+          mvn -B org.openrewrite.maven:rewrite-maven-plugin:run spotless:apply -DskipTests --file lyo-client-samples/pom.xml
+          git add -A
+          if [ -z "$(git -C ./ status --porcelain)" ]; then
+            echo "rewrite PASS"
+          else
+            git -C ./ status --porcelain
+            echo "rewrite FAIL; run 'mvn -B org.openrewrite.maven:rewrite-maven-plugin:run spotless:apply -DskipTests --file lyo-client-samples/pom.xml' locally" >&2
+            exit 1
+          fi
