build: run rewrite on build

diff --git a/.github/workflows/maven-client.yml b/.github/workflows/maven-client.yml
--- a/.github/workflows/maven-client.yml
+++ b/.github/workflows/maven-client.yml
@@ -45,6 +45,21 @@ jobs:
       - name: Build Lyo Client samples
         run: |
           mvn -B clean verify --file lyo-client-samples/pom.xml
-      - name: Enforce code style
+      - name: Run Spotless (Maven plugin)
         run: |
-          mvn -B spotless:check --file lyo-client-samples/pom.xml
+          mvn -B spotless:apply -P!enforcer --file lyo-client-samples/pom.xml
+          if [ -z "$(git -C ./ status --porcelain)" ]; then
+            echo "Spotless PASS"
+          else
+            echo "Spotless FAIL; run 'mvn validate -Pspotless --file lyo-client-samples/pom.xml' locally" >&2
+            exit 1
+          fi
+      - name: Run OpenRewrite (Maven plugin)
+        run: |
+          mvn -B org.openrewrite.maven:rewrite-maven-plugin:run spotless:apply -DskipTests -P'!enforcer' --file lyo-client-samples/pom.xml
+          if [ -z "$(git -C ./ status --porcelain)" ]; then
+            echo "rewrite PASS"
+          else
+            echo "rewrite FAIL; run 'mvn org.openrewrite.maven:rewrite-maven-plugin:run --file lyo-client-samples/pom.xml' locally" >&2
+            exit 1
+          fi
